version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./port_folio:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
