version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
